tap "homebrew/cask-drivers"
# tap "rusty-ferris-club/tap"
tap "sergiomss/homebrew-tap"

brew "zsh"
brew "fzf"
brew "asdf"
brew "jq"
brew "awscli"
brew "jenv"
brew "go"
brew "colordiff"
brew "pre-commit"
brew "tfenv"
brew "circleci"
brew "git"
brew "maven"
brew "maven-completion"
brew "gradle"
brew "nvm"
brew "yarn"
brew "pyenv"
brew "make"
brew "goreleaser"
brew "watch"
brew "ipcalc"
brew "tomcat"
brew "java11"
brew "python-yq"
brew "gh"
brew "wget"
brew "tree"
brew "k9s"
brew "kubectl"

# brew "rusty-ferris-club/tap/shellclear"
brew "sergiomss/tap/ks"

# Casks
cask "jetbrains-toolbox"
cask "slack"
cask "docker"
cask "google-chrome"
cask "postman"
cask "visual-studio-code"
cask "iterm2"
cask "firefox"
cask "spotify"
cask "signal"
cask "discord"
cask "steam"
# cask "logitech-options"